DROP TABLE IF EXISTS usuario_salud;
DROP TABLE IF EXISTS historia_clinica_documento;
DROP TABLE IF EXISTS historia_clinica;
DROP TABLE IF EXISTS admin_hcen;
DROP TABLE IF EXISTS jwt_sessions;
DROP SEQUENCE IF EXISTS usuario_salud_id_seq;

CREATE TABLE admin_hcen (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    passwordHash VARCHAR(255) NOT NULL,
    firstName VARCHAR(100) NOT NULL,
    lastName VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_login TIMESTAMP
);

CREATE TABLE jwt_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id VARCHAR(100) NOT NULL,
    jwt_token VARCHAR(4096) NOT NULL,
    issued_at TIMESTAMP NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    last_used_at TIMESTAMP,
    active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE INDEX idx_jwt_token ON jwt_sessions (jwt_token);
CREATE INDEX idx_client_id ON jwt_sessions (client_id);
CREATE INDEX idx_expires_at ON jwt_sessions (expires_at);

CREATE TABLE historia_clinica (
    id VARCHAR(36) PRIMARY KEY,
    fec_creacion TIMESTAMP NOT NULL,
    fec_actualizacion TIMESTAMP,
    usuario_cedula VARCHAR(20) NOT NULL
);

CREATE TABLE historia_clinica_documento (
    id VARCHAR(36) PRIMARY KEY,
    historia_id VARCHAR(36) NOT NULL,
    documento_id VARCHAR(36) NOT NULL,
    tenant_id VARCHAR(36) NOT NULL,
    fec_registro TIMESTAMP NOT NULL,
    CONSTRAINT fk_hist_doc_historia FOREIGN KEY (historia_id) REFERENCES historia_clinica(id),
    CONSTRAINT uk_hist_doc UNIQUE (historia_id, documento_id)
);

CREATE INDEX idx_hist_doc_historia ON historia_clinica_documento (historia_id);
CREATE INDEX idx_hist_doc_documento ON historia_clinica_documento (documento_id);

CREATE SEQUENCE usuario_salud_id_seq START WITH 1;

CREATE TABLE usuario_salud (
    cedula VARCHAR(20) NOT NULL,
    id BIGINT NOT NULL DEFAULT NEXT VALUE FOR usuario_salud_id_seq,
    historia_clinica_id VARCHAR(36),
    tipo_documento VARCHAR(20),
    fecha_nacimiento DATE NOT NULL,
    email VARCHAR(255) NOT NULL,
    email_verificado BOOLEAN DEFAULT TRUE,
    telefono VARCHAR(20),
    direccion VARCHAR(500),
    nombre_completo VARCHAR(255),
    primer_nombre VARCHAR(100) NOT NULL,
    segundo_nombre VARCHAR(100),
    primer_apellido VARCHAR(100) NOT NULL,
    segundo_apellido VARCHAR(100),
    active BOOLEAN DEFAULT TRUE NOT NULL,
    notificaciones_habilitadas BOOLEAN DEFAULT TRUE NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    last_login TIMESTAMP,
    PRIMARY KEY (cedula, id),
    CONSTRAINT fk_usuario_historia FOREIGN KEY (historia_clinica_id) REFERENCES historia_clinica(id)
);
